### ISSUE TITLE
SudokuPad links [suggestion] 

### ISSUE THREAD

**Issue by andyg1001** [mjr5749/ctc-database#1]
Hey there, fantastic resource!

Would it be possible to have a direct link also to the puzzles so that they can be played. The links are included in the videos, but it would be really nice to skip the step of viewing the video in order to play the puzzle.

What would be amazing is if the link opened directly into the SudokuPad app for those who had it. At the moment, it is necessary to first view the video, then locate the right link to open the webpage then click on the open in SudokuPad link. I'd love to be able to automate this - the latest update to SudokuPad sadly deletes all the stored data and I now have to repopulate a good 100 puzzles!

As I say, you have a fantastic resource here - a real lifeline!!

**Comment by andyg1001** [comment]
I don't know if this helps, but the following is a very simple bash script that scrapes the youtube link for the puzzle ID and then retrieves the SudokuPad URL.  If successful, the script generates two lines: the first is the link to play on the web, the second to launch it in the app...

```
#!/bin/bash

YOUTUBE_LINK='https://www.youtube.com/watch?v=hwUc0NGdnuM'

WEB_LINK_BASE='https://app.crackingthecryptic.com/sudoku/'
PUZZLE_ID="$(curl -Ss "$YOUTUBE_LINK" | sed -n "s,.*$WEB_LINK_BASE\([0-9a-zA-Z]\+\).*,\1,p")"
SUDOKUPAD="$(curl -w "%{url_effective}\n" -ILSs "https://sudokupad.svencodes.com/sudoku/$PUZZLE_ID" -o /dev/null)"

echo "$WEB_LINK_BASE$PUZZLE_ID"
echo "sudokupad:/${SUDOKUPAD#https://sudokupad.svencodes.com}"
```

I'm sure there must be a better way to extract the description from a youtube video (they have an API it seems, but I didn't find an easy way to do this).  Also the description doesn't always cleanly contain the URL of the puzzle on its own line.  However, the above seems to work in a handful of tests I ran.

I would like to try the script against the URLs in the sqlite database this repository generates. I'll see if I can do that and report back if it is successful 😊

**Comment by mjr5749** [comment]
Hello! Thanks for the suggestion, and I'm glad you are finding the site useful.

While it would be technically feasible to pull the puzzle links into the site, I chose not to add them here for consistency with the source catalogue -- as described on the FAQ page here:
> https://docs.google.com/spreadsheets/d/1rVqAjm-l_Urjd3TNmIc3SmTmz_OlgSoBuhY7RPgiuRg/edit#gid=1894874937
> 
> **Why are there no links to the puzzles in the catalogue? Will you include these?**
> After careful consideration, it was decided to not include links to the specific puzzles in the catalogue. This was done in full agreement with CTC.
